# -*- coding: utf-8 -*-
"""Taufan Riztian Anwari.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhtsUe75RXKfktqpbCSFIwleDQrJUvJt
"""

# input
nama = input("Masukan nama :")
umur = int(input("masukan umur :"))

# output
print ("Halo", nama)
print ("Umur Anda:", umur, "tahun")
print (f"Tahun lahir Anda: {2025 - umur}") # f-string

# input dari pengguna

jari_jari = float (input("Jari - jari lingkaran :"))
luas = 3.14 * jari_jari ** 2
print( 'Luas lingkaran =' ,luas)

#input math

# jari-jari lingkaran
r = float(input("Masukan jari-jari lingkaran: "))

# rumus keliling lingkaran
keliling = 2 * 3.14  * r

print (f"keliling lingkaran dengan jari-jari {r} adalah {keliling:}")

import math

# Input

Sisi_Alas = float(input("Masukan sisi Alas : "))
Sisi_tinggi = float(input("Masukan sisi Tinggi : "))

# rumus sisi miring

Sisi_miring = math.sqrt(Sisi_Alas ** 2 + Sisi_tinggi ** 2)

# Perhitungan

Keliling = Sisi_Alas + Sisi_tinggi + Sisi_miring
Luas = (Sisi_Alas * Sisi_tinggi)/2

# Output

print(f"jadi untuk Keliling segitiga : {Keliling} cm")
print(f"dan Luas : {Luas} cm")

import math

# Input

Sisi_A = float(input("Masukan sisi A : "))
Sisi_B = float(input("Masukan sisi B : "))
Sisi_C = float(input("Masukan sisi C : "))
Sisi_D = float(input("Masukan sisi D : "))
Tinggi = float(input("Masukan Tinggi : "))

# Perhitungan

luas = Sisi_A * Sisi_B * Tinggi / 2
keliling = Sisi_A + Sisi_B + Sisi_C + Sisi_D

# Output

print(f"Luas Trapesium: {luas}")
print(f"Keliling Trapesium: {keliling}")

import math

def input_angka(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            print("Masukkan angka yang valid.")

def tambah(a, b):
    return a + b

def kurang(a, b):
    return a - b

def kali(a, b):
    return a * b

def bagi(a, b):
    if b == 0:
        return "Error: Pembagian oleh nol"
    else:
        return a / b

def pangkat(base, eksponen):
    return base ** eksponen

def akar_kuadrat(n):
    if n < 0:
        return "Error: Bilangan negatif tidak memiliki akar real"
    else:
        return math.sqrt(n)

def celsius_ke_fahrenheit(c):
    return (c * 9/5) + 32

def fahrenheit_ke_celsius(f):
    return (f - 32) * 5/9

def celsius_ke_kelvin(c):
    return c + 273.15

def kelvin_ke_celsius(k):
    return k - 273.15

def fahrenheit_ke_kelvin(f):
    c = fahrenheit_ke_celsius(f)
    return celsius_ke_kelvin(c)

def kelvin_ke_fahrenheit(k):
    c = kelvin_ke_celsius(k)
    return celsius_ke_fahrenheit(c)

while True:
    print("\nPilih jenis kalkulator:")
    print("1. Operasi Dasar")
    print("2. Perpangkatan dan Akar Kuadrat")
    print("3. Konversi Suhu")
    print("4. Keluar")

    pilihan = input("Masukkan pilihan (1/2/3/4): ")

    if pilihan == '4':
        print("Keluar dari program.")
        break

    elif pilihan == '1':
        num1 = input_angka("Masukkan bilangan pertama: ")
        operator = input("Masukkan operator (+, -, *, /): ")
        num2 = input_angka("Masukkan bilangan kedua: ")

        if operator == '+':
            hasil = tambah(num1, num2)
        elif operator == '-':
            hasil = kurang(num1, num2)
        elif operator == '*':
            hasil = kali(num1, num2)
        elif operator == '/':
            hasil = bagi(num1, num2)
        else:
            hasil = "Operator tidak valid"

        print(f"Hasil: {hasil}")

    elif pilihan == '2':
        print("Pilih operasi:")
        print("1. Perpangkatan")
        print("2. Akar Kuadrat")
        sub_pilihan = input("Masukkan pilihan (1/2): ")

        if sub_pilihan == '1':
            base = input_angka("Masukkan basis: ")
            eksponen = input_angka("Masukkan eksponen: ")
            hasil = pangkat(base, eksponen)
            print(f"Hasil: {hasil}")
        elif sub_pilihan == '2':
            num = input_angka("Masukkan bilangan: ")
            hasil = akar_kuadrat(num)
            print(f"Hasil: {hasil}")
        else:
            print("Pilihan tidak valid")

    elif pilihan == '3':
        print("Pilih unit suhu awal:")
        print("C. Celsius")
        print("F. Fahrenheit")
        print("K. Kelvin")
        unit_awal = input("Masukkan unit (C/F/K): ").upper()

        print("Pilih unit suhu tujuan:")
        unit_tujuan = input("Masukkan unit (C/F/K): ").upper()

        suhu = input_angka("Masukkan suhu: ")

        if unit_awal == 'C' and unit_tujuan == 'F':
            hasil = celsius_ke_fahrenheit(suhu)
        elif unit_awal == 'C' and unit_tujuan == 'K':
            hasil = celsius_ke_kelvin(suhu)
        elif unit_awal == 'F' and unit_tujuan == 'C':
            hasil = fahrenheit_ke_celsius(suhu)
        elif unit_awal == 'F' and unit_tujuan == 'K':
            hasil = fahrenheit_ke_kelvin(suhu)
        elif unit_awal == 'K' and unit_tujuan == 'C':
            hasil = kelvin_ke_celsius(suhu)
        elif unit_awal == 'K' and unit_tujuan == 'F':
            hasil = kelvin_ke_fahrenheit(suhu)
        elif unit_awal == unit_tujuan:
            hasil = suhu
        else:
            hasil = "Konversi tidak valid"

        print(f"Hasil konversi: {hasil}")

    else:
        print("Pilihan tidak valid. Silakan coba lagi.")

def sistem_informasi_akademik():
    print("\n=== Input: Sistem Informasi Akademik ===")
    nama = input("Nama Mahasiswa: ")
    nim = input("NIM: ")
    ipk = float(input("IPK: "))
    sudah_lulus = input("Sudah lulus? (y/n): ").lower() == 'y'

    mata_kuliah = input("Masukkan daftar mata kuliah (pisahkan dengan koma): ").split(',')
    mata_kuliah = [mk.strip() for mk in mata_kuliah]

    nilai = {}
    for mk in mata_kuliah:
        n = int(input(f"Nilai untuk {mk}: "))
        nilai[mk] = n

    mahasiswa = {
        "nama": nama,
        "nim": nim,
        "ipk": ipk,
        "sudah_lulus": sudah_lulus,
        "mata_kuliah": mata_kuliah,
        "nilai": nilai
    }

    print("\n--- Data Mahasiswa ---")
    for k, v in mahasiswa.items():
        print(f"{k.capitalize()}: {v} ({type(v).__name__})")


def aplikasi_ecommerce():
    print("\n=== Input: Aplikasi E-Commerce ===")
    nama_produk = input("Nama Produk: ")
    harga = int(input("Harga (Rp): "))
    diskon = float(input("Diskon (misal: 0.2 untuk 20%): "))
    stok = int(input("Jumlah Stok: "))
    kategori = input("Kategori Produk (pisahkan dengan koma): ").split(',')
    kategori = [k.strip() for k in kategori]
    tersedia = input("Apakah produk tersedia? (y/n): ").lower() == 'y'

    produk = {
        "nama_produk": nama_produk,
        "harga": harga,
        "diskon": diskon,
        "stok": stok,
        "kategori": kategori,
        "tersedia": tersedia
    }

    print("\n--- Data Produk ---")
    for k, v in produk.items():
        print(f"{k.replace('_', ' ').capitalize()}: {v} ({type(v).__name__})")


def sistem_reservasi_hotel():
    print("\n=== Input: Sistem Reservasi Hotel ===")
    nama_tamu = input("Nama Tamu: ")
    nomor_kamar = int(input("Nomor Kamar: "))
    check_in = input("Tanggal Check-in (YYYY-MM-DD): ")
    check_out = input("Tanggal Check-out (YYYY-MM-DD): ")
    jumlah_malam = int(input("Jumlah Malam: "))
    total_harga = float(input("Total Harga (Rp): "))
    sudah_dibayar = input("Sudah dibayar? (y/n): ").lower() == 'y'

    reservasi = {
        "nama_tamu": nama_tamu,
        "nomor_kamar": nomor_kamar,
        "check_in": check_in,
        "check_out": check_out,
        "jumlah_malam": jumlah_malam,
        "total_harga": total_harga,
        "sudah_dibayar": sudah_dibayar
    }

    print("\n--- Data Reservasi ---")
    for k, v in reservasi.items():
        print(f"{k.replace('_', ' ').capitalize()}: {v} ({type(v).__name__})")


def main():
    while True:
        print("\n=== Menu Identifikasi Tipe Data ===")
        print("1. Sistem Informasi Akademik")
        print("2. Aplikasi E-Commerce")
        print("3. Sistem Reservasi Hotel")
        print("4. Keluar")

        pilihan = input("Pilih menu (1/2/3/4): ")

        if pilihan == '1':
            sistem_informasi_akademik()
        elif pilihan == '2':
            aplikasi_ecommerce()
        elif pilihan == '3':
            sistem_reservasi_hotel()
        elif pilihan == '4':
            print("Terima kasih! 👋")
            break
        else:
            print("Pilihan tidak valid. Coba lagi.")

if __name__ == "__main__":
    main()

def hitung_nilai_akhir(tugas, uts, uas):
    return (0.3 * tugas) + (0.3 * uts) + (0.4 * uas)

def tentukan_kategori(nilai_akhir):
    if nilai_akhir >= 85:
        return 'A', 'Sangat Baik'
    elif nilai_akhir >= 75:
        return 'B', 'Baik'
    elif nilai_akhir >= 65:
        return 'C', 'Cukup'
    elif nilai_akhir >= 50:
        return 'D', 'Kurang'
    else:
        return 'E', 'Sangat Kurang'

def keterangan_lulus(nilai_huruf):
    return "LULUS" if nilai_huruf in ['A', 'B', 'C'] else "TIDAK LULUS"

def main():
    print("=== Program Penilaian Mahasiswa ===")
    nama = input("Nama Mahasiswa: ")

    try:
        tugas = float(input("Nilai Tugas (0-100): "))
        uts = float(input("Nilai UTS (0-100): "))
        uas = float(input("Nilai UAS (0-100): "))

        nilai_akhir = hitung_nilai_akhir(tugas, uts, uas)
        nilai_huruf, deskripsi = tentukan_kategori(nilai_akhir)
        status = keterangan_lulus(nilai_huruf)

        print("\n--- Hasil Penilaian ---")
        print(f"Nama         : {nama}")
        print(f"Nilai Akhir  : {nilai_akhir:.2f}")
        print(f"Nilai Huruf  : {nilai_huruf}")
        print(f"Deskripsi    : {deskripsi}")
        print(f"Keterangan   : {status}")

    except ValueError:
        print("Input harus berupa angka!")

if __name__ == "__main__":
    main()

# Simulasi data awal pengguna
akun = {
    "pin": "1234",
    "saldo": 10000000000  # dalam Rupiah
}

def verifikasi_pin():
    for i in range(3):
        pin_input = input("Masukkan PIN: ")
        if pin_input == akun["pin"]:
            return True
        else:
            print("PIN salah.")
    print("3x percobaan gagal. Kartu diblokir.")
    return False

def cek_saldo():
    print(f"Saldo Anda saat ini: ${akun['saldo']:,}")

def tarik_tunai():
    jumlah = int(input("Masukkan jumlah yang ingin ditarik: $"))
    if jumlah <= 0:
        print("Jumlah tidak valid.")
    elif jumlah > akun["saldo"]:
        print("Saldo tidak mencukupi.")
    else:
        akun["saldo"] -= jumlah
        print(f"Berhasil menarik ${jumlah:,}. Saldo tersisa: ${akun['saldo']:,}")

def setor_tunai():
    jumlah = int(input("Masukkan jumlah yang ingin disetor: $"))
    if jumlah <= 0:
        print("Jumlah tidak valid.")
    else:
        akun["saldo"] += jumlah
        print(f"Berhasil menyetor ${jumlah:,}. Saldo sekarang: ${akun['saldo']:,}")

def transfer():
    rekening = input("Masukkan nomor rekening tujuan: ")
    jumlah = int(input("Masukkan jumlah yang ingin ditransfer: $"))
    if jumlah <= 0:
        print("Jumlah tidak valid.")
    elif jumlah > akun["saldo"]:
        print("Saldo tidak mencukupi untuk transfer.")
    else:
        akun["saldo"] -= jumlah
        print(f"Transfer ke {rekening} sebesar ${jumlah:,} berhasil. Sisa saldo: ${akun['saldo']:,}")

def ganti_pin():
    pin_lama = input("Masukkan PIN lama: ")
    if pin_lama != akun["pin"]:
        print("PIN lama salah.")
        return
    pin_baru = input("Masukkan PIN baru (4 digit): ")
    if len(pin_baru) != 4 or not pin_baru.isdigit():
        print("PIN baru harus terdiri dari 4 digit angka.")
        return
    akun["pin"] = pin_baru
    print("PIN berhasil diubah.")

def menu_atm():
    while True:
        print("\n=== Menu ATM ===")
        print("1. Cek Saldo")
        print("2. Tarik Tunai")
        print("3. Setor Tunai")
        print("4. Transfer")
        print("5. Ganti PIN")
        print("6. Keluar")

        pilihan = input("Pilih menu (1-6): ")
        if pilihan == "1":
            cek_saldo()
        elif pilihan == "2":
            tarik_tunai()
        elif pilihan == "3":
            setor_tunai()
        elif pilihan == "4":
            transfer()
        elif pilihan == "5":
            ganti_pin()
        elif pilihan == "6":
            print("Terima kasih telah menggunakan ATM.")
            break
        else:
            print("Pilihan tidak valid.")

def main():
    print("=== Selamat datang di ATM ===")
    if verifikasi_pin():
        menu_atm()

if __name__ == "__main__":
    main()

# Input dari pengguna
a = float(input("Masukkan bilangan pertama: "))
b = float(input("Masukkan bilangan kedua: "))
c = float(input("Masukkan bilangan ketiga: "))

# 1. Menggunakan nested if
print("\n=== Menggunakan Nested If ===")
if a >= b:
    if a >= c:
        maks = a
    else:
        maks = c
else:
    if b >= c:
        maks = b
    else:
        maks = c
print("Nilai maksimum (nested if):", maks)

# 2. Menggunakan operator logika
print("\n=== Menggunakan Operator Logika ===")
if (a >= b) and (a >= c):
    maks = a
elif (b >= a) and (b >= c):
    maks = b
else:
    maks = c
print("Nilai maksimum (operator logika):", maks)

# 3. Menggunakan fungsi max()
print("\n=== Menggunakan Fungsi max() ===")
maks = max(a, b, c)
print("Nilai maksimum (fungsi max):", maks)
